import 'server-only'
import crypto from 'node:crypto'
import { and, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { portalEvents, portalStudents } from '@/lib/db/schema'

export type PortalRole = 'student' | 'admin'
export type PortalSession = { role: PortalRole; computerNumber?: string; expiresAt: number }

const secret = () => { const value = process.env.PALACE_SECRET_KEY; if (!value && process.env.NODE_ENV === 'production') throw new Error('PALACE_SECRET_KEY is required in production'); return value || 'local-development-only-secret' }
const sign = (value: string) => crypto.createHmac('sha256', secret()).update(value).digest('base64url')
export function issueSession(session: Omit<PortalSession, 'expiresAt'>, ttlSeconds = 60 * 60 * 8) { const body = Buffer.from(JSON.stringify({ ...session, expiresAt: Date.now() + ttlSeconds * 1000 })).toString('base64url'); return `${body}.${sign(body)}` }
export function readSession(request: Request): PortalSession | null { const value = request.headers.get('authorization')?.replace(/^Bearer\s+/i, '') || request.headers.get('x-palace-session'); if (!value) return null; const [body, signature] = value.split('.'); if (!body || !signature || !secret() || signature.length !== sign(body).length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(sign(body)))) return null; try { const session = JSON.parse(Buffer.from(body, 'base64url').toString()) as PortalSession; return session.expiresAt > Date.now() ? session : null } catch { return null } }
export function isComputerNumber(value: unknown): value is string { return typeof value === 'string' && /^\d{10}$/.test(value) }
export function currentSemester() { const month = new Date().getUTCMonth() + 1; return month <= 6 ? 1 : 2 }
export async function signupStudent(input: { studentNumber: string; computerNumber: string; email: string; firstName: string; lastName: string; nationalId: string; passwordHash: string }) { return db.transaction(async (tx) => { const existing = await tx.select({ id: portalStudents.id }).from(portalStudents).where(and(eq(portalStudents.studentNumber, input.studentNumber), eq(portalStudents.nationalId, input.nationalId))).for('update'); if (existing.length) throw Object.assign(new Error('Student already registered'), { code: 'CONFLICT' }); const student = { id: crypto.randomUUID(), ...input, status: 'pending', academicLevel: 1, academicYear: new Date().getUTCFullYear(), semesterSignIns: 0, photoFresh: false }; const [created] = await tx.insert(portalStudents).values(student).returning(); await tx.insert(portalEvents).values({ id: crypto.randomUUID(), computerNumber: input.computerNumber, event: 'SIGN_UP', academicYear: student.academicYear }); return created }) }
export async function getStudentByComputerNumber(computerNumber: string) { const [student] = await db.select().from(portalStudents).where(eq(portalStudents.computerNumber, computerNumber)); return student || null }
export async function semesterSignIn(computerNumber: string) { return db.transaction(async (tx) => { const [student] = await tx.select().from(portalStudents).where(eq(portalStudents.computerNumber, computerNumber)).for('update'); if (!student) throw Object.assign(new Error('Student not found'), { code: 'NOT_FOUND' }); const semester = currentSemester(); if (student.lastSignInSemester === semester && student.semesterSignIns >= 2) throw Object.assign(new Error('Semester sign-in limit reached'), { code: 'CONFLICT' }); const nextCount = student.lastSignInSemester === semester ? student.semesterSignIns + 1 : 1; const level = nextCount >= 2 && student.lastSignInSemester === semester ? student.academicLevel + 1 : student.academicLevel; const [updated] = await tx.update(portalStudents).set({ semesterSignIns: nextCount, lastSignInSemester: semester, lastSignInAt: new Date(), academicLevel: level, updatedAt: new Date() }).where(eq(portalStudents.computerNumber, computerNumber)).returning(); await tx.insert(portalEvents).values({ id: crypto.randomUUID(), computerNumber, event: 'SIGN_IN', semester, academicYear: updated.academicYear }); return updated }) }
